In [1]:
import os

os.getcwd()

'd:\\Google Drive(awekim@handong.edu)\\[Project]\\[Quantum]\\02_Analysis'

In [3]:
import pandas as pd

# inst = pd.read_csv('../05_허지수박사/quant_inst_ed_eu.csv', encoding='ISO-8859-1')
inst = pd.read_csv('QuanTech_R/R file/quant_inst_ed_eu_val.csv', encoding='ISO-8859-1')
inst.head()

,Unnamed: 0,pubid,qc_category,institution_id_te,organization,suborganization,full_address,city,state,country,zip,pubyear,organization_clean
0,1,8064916,qc111,77541063,UNIV PATRAS,SCH NAT SCI,"UNIV PATRAS, SCH NAT SCI, DEPT MAT SCI, PATRAS...",PATRAS,NaN,GREECE,26504,2004,UNIV PATRAS
1,2,8064916,qc111,77541064,UNIV PATRAS,DEPT MAT SCI,"UNIV PATRAS, SCH NAT SCI, DEPT MAT SCI, PATRAS...",PATRAS,NaN,GREECE,26504,2004,UNIV PATRAS
2,3,8064916,qc111,84907542,UNIVERSITY OF PATRAS,SCH NAT SCI,"UNIV PATRAS, SCH NAT SCI, DEPT MAT SCI, PATRAS...",PATRAS,NaN,GREECE,26504,2004,UNIV PATRAS
3,4,8064916,qc111,84907543,UNIVERSITY OF PATRAS,DEPT MAT SCI,"UNIV PATRAS, SCH NAT SCI, DEPT MAT SCI, PATRAS...",PATRAS,NaN,GREECE,26504,2004,UNIV PATRAS
4,5,8064916,qc111,70835111,UNIV DURHAM,DEPT PHYS,"UNIV DURHAM, DEPT PHYS, DURHAM DH1 3LE, ENGLAND",DURHAM,NaN,ENGLAND,DH1 3LE,2004,UNIV DURHAM

In [3]:
inst.loc[inst.qc_category=="qc224"]

Empty DataFrame
Columns: [Unnamed: 0, pubid, qc_category, institution_id_te, organization, suborganization, full_address, city, state, country, zip, pubyear, organization_clean]
Index: []

In [4]:
# Replace abbreviations e.g., 'UNIV' with 'UNIVERSITY' and 'INST' with 'INSTITUTION' in the 'organization' column
inst['standardized_organization'] = inst['organization'].str.replace(r'\bINST\b', 'INSTITUTION', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bHOP\b', 'HOSPITAL', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bHOSP\b', 'HOSPITAL', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bTECHNOL\b', 'TECHNOLOGY', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bMED\b', 'MEDICAL', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bNATL\b', 'NATIONAL', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bCTR\b', 'CENTRE', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bNUCL\b', 'NUCLEAR', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bRES\b', 'RESEARCH', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bPUBL\b', 'PUBLIC', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bAGCY\b', 'AGENCY', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bHLTH\b', 'HEALTH', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bSERV\b', 'SERVICE', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bCOLL\b', 'COLLEGE', regex=True)
inst['standardized_organization'] = inst['organization'].str.replace(r'\bMED\b', 'MEDICAL', regex=True)

In [5]:
# Replace "UNIV" with "UNIVERSITY" and "UNIVERSITY OF" in the 'standardized_organization' column

def modify_organization_name(name):
    # Check if the value is a string
    if isinstance(name, str):
        # Check if already correctly formatted or not containing "UNIV"
        if "UNIVERSITY" in name or "UNIV" not in name:
            return name
        elif name.endswith('UNIV'):
            return name.replace('UNIV', 'UNIVERSITY')
        else:
            return name.replace('UNIV', 'UNIVERSITY OF')
    else:
        # Return the value as it is if it's not a string
        return name

inst['standardized_organization'] = inst['standardized_organization'].apply(modify_organization_name)
inst[['organization', 'standardized_organization']].head()

           organization standardized_organization
0           UNIV PATRAS      UNIVERSITY OF PATRAS
1           UNIV PATRAS      UNIVERSITY OF PATRAS
2  UNIVERSITY OF PATRAS      UNIVERSITY OF PATRAS
3  UNIVERSITY OF PATRAS      UNIVERSITY OF PATRAS
4           UNIV DURHAM      UNIVERSITY OF DURHAM

In [26]:
# inst.loc[inst.standardized_organization=='UNIVERSITY OF TORONTO']
# inst.loc[inst.organization=='UNIVERSIDADE DO PORTO']

,Unnamed: 0,pubid,qc_category,institution_id_te,organization,suborganization,full_address,city,state,country,zip,pubyear,organization_clean,standardized_organization
2475,2476,8881413,qc221,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO
2476,2477,8881413,qc221,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO
2485,2486,8881413,qc43,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO
2486,2487,8881413,qc43,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO
8891,8892,24770749,qc422,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2014,UNIV TORONTO,UNIVERSITY OF TORONTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237618,237619,38848619,qc43,86378196,UNIVERSITY OF TORONTO,DEPT PHARMACEUT SCI,"UNIV TORONTO, LESLIE DAN FAC PHARM, DEPT PHARM...",TORONTO,ON,CANADA,M5S 3M2,2019,UNIV TORONTO,UNIVERSITY OF TORONTO
244484,244485,46154719,qc43,80416089,UNIV TORONTO,DEPT CHEM,"UNIV TORONTO, DEPT CHEM, TORONTO, ON M5S 3H6, ...",TORONTO,ON,CANADA,M5S 3H6,2021,UNIV TORONTO,UNIVERSITY OF TORONTO
244485,244486,46154719,qc43,82949920,UNIVERSITY OF TORONTO,DEPT CHEM,"UNIV TORONTO, DEPT CHEM, TORONTO, ON M5S 3H6, ...",TORONTO,ON,CANADA,M5S 3H6,2021,UNIV TORONTO,UNIVERSITY OF TORONTO
244486,244487,46154719,qc43,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2021,UNIV TORONTO,UNIVERSITY OF TORONTO
244487,244488,46154719,qc43,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2021,UNIV TORONTO,UNIVERSITY OF TORONTO

In [6]:
inst.standardized_organization.value_counts()

standardized_organization
CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE (CNRS)    9080
CONSIGLIO NAZIONALE DELLE RICERCHE (CNR)               2584
UNIVERSITY OF CAMBRIDGE                                2387
UNIVERSITY OF OXFORD                                   2280
MAX PLANCK SOCIETY                                     2071
                                                       ...
CIDETEC IK4                                               1
JOANNEUM RES FORSCH GESELL MBH                            1
TRIDON JENNERSDORF GMBH                                   1
SUPERCOMP CTR GALICIA CESGA                               1
DELHI TECHNOLOGICAL UNIVERSITY                            1
Name: count, Length: 9146, dtype: int64

In [9]:
### import fuzzywuzzy package

# !pip install fuzzywuzzy python-Levenshtein

In [7]:
from fuzzywuzzy import fuzz
from collections import defaultdict

# This function will return True if two names are similar based on a set threshold
def are_similar(name1, name2, threshold=90):
    return fuzz.token_sort_ratio(name1, name2) >= threshold

In [8]:
# Create clusters of similar names
clusters = defaultdict(list)
names = inst['standardized_organization'].unique()

for name in names:
    found_cluster = False
    for cluster_name in clusters:
        if are_similar(name, cluster_name):
            clusters[cluster_name].append(name)
            found_cluster = True
            break
    if not found_cluster:
        clusters[name].append(name)

# For each cluster, select the most common name as the standard name
standard_names = {}
for cluster, names in clusters.items():
    standard_name = max(names, key=names.count)  
    for name in names:
        standard_names[name] = standard_name

# Apply the standardization
inst['final_standardized_organization'] = inst['standardized_organization'].map(standard_names)

# Check the result
print(inst[['standardized_organization', 'final_standardized_organization']])

                   standardized_organization  \
0                       UNIVERSITY OF PATRAS
1                       UNIVERSITY OF PATRAS
2                       UNIVERSITY OF PATRAS
3                       UNIVERSITY OF PATRAS
4                       UNIVERSITY OF DURHAM
...                                      ...
244930               UNIVERSITY OF HONG KONG
244931              DELHI TECHNOL UNIVERSITY
244932        DELHI TECHNOLOGICAL UNIVERSITY
244933  ALPEN ADRIA UNIVERSITY OF KLAGENFURT
244934              UNIVERSITY OF KLAGENFURT

             final_standardized_organization
0                       UNIVERSITY OF PATRAS
1                       UNIVERSITY OF PATRAS
2                       UNIVERSITY OF PATRAS
3                       UNIVERSITY OF PATRAS
4                       UNIVERSITY OF DURHAM
...                                      ...
244930          CITY UNIVERSITY OF HONG KONG
244931              DELHI TECHNOL UNIVERSITY
244932       TECHNOLOGICAL UNIVERSITY DUBLIN
244933  ALPEN ADRIA UNIVERSITY OF KLAGENFURT
244934              UNIVERSITY OF KLAGENFURT

[244935 rows x 2 columns]

In [7]:
inst.loc[inst.standardized_organization=='UNIVERSITY OF TORONTO']
#inst.loc[inst.standardized_organization=='UNIVERSITY OF PORTO']

,Unnamed: 0,pubid,qc_category,institution_id_te,organization,suborganization,full_address,city,state,country,zip,pubyear,organization_clean,standardized_organization,final_standardized_organization
2475,2476,8881413,qc221,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
2476,2477,8881413,qc221,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
2485,2486,8881413,qc43,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
2486,2487,8881413,qc43,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2005,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
8891,8892,24770749,qc422,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2014,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237618,237619,38848619,qc43,86378196,UNIVERSITY OF TORONTO,DEPT PHARMACEUT SCI,"UNIV TORONTO, LESLIE DAN FAC PHARM, DEPT PHARM...",TORONTO,ON,CANADA,M5S 3M2,2019,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
244484,244485,46154719,qc43,80416089,UNIV TORONTO,DEPT CHEM,"UNIV TORONTO, DEPT CHEM, TORONTO, ON M5S 3H6, ...",TORONTO,ON,CANADA,M5S 3H6,2021,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
244485,244486,46154719,qc43,82949920,UNIVERSITY OF TORONTO,DEPT CHEM,"UNIV TORONTO, DEPT CHEM, TORONTO, ON M5S 3H6, ...",TORONTO,ON,CANADA,M5S 3H6,2021,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
244486,244487,46154719,qc43,80408511,UNIV TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2021,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO
244487,244488,46154719,qc43,82171350,UNIVERSITY OF TORONTO,DEPT PHYS,"UNIV TORONTO, DEPT PHYS, TORONTO, ON M5S 1A7, ...",TORONTO,ON,CANADA,M5S 1A7,2021,UNIV TORONTO,UNIVERSITY OF TORONTO,UNIVERSITY OF PORTO

In [9]:
inst.loc[inst['standardized_organization'] == 'UNIVERSITY OF TORONTO', 'final_standardized_organization'] = 'UNIVERSITY OF TORONTO'

In [10]:
# Manual Edits
# if 'Source' and 'Target' columns contain 'A DUPLICATED NAME OF THE ORGANIZATION',
# then replace it with 'MERGED NAME OF THE ORGANIZATION'
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE (CNRS)', 'CNRS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CZECH ACAD SCI', 'CZECH ACADEMY OF SCIENCES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE (CNRS) - INSTITUTE FOR ENGINEERING & SYSTEMS SCIENCES (INSIS)', 'CNRS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('KATHOLIEKE UNIVERSITY OF LEUVEN', 'KU LEUVEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLITECN MILAN', 'POLYTECHNIC UNIVERSITY OF MILAN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ISTITUTO NANOSCIENZE (NANO-CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CONSIGLIO NAZIONALE DELLE RICERCHE (CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ISTITUTO NAZIONALE DI FISICA NUCLEARE', 'IST NAZL FIS NUCL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLISH ACADEMY OF SCIENCES', 'POLISH ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CNRS - INSTITUTE OF PHYSICS (INP)', 'CNRS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('TECHNICAL UNIVERSITY OF MUNICH', 'TECH UNIVERSITY OF MUNCHEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY COLLEGE LONDON', 'UCL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF PARIS 11', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST QUANTUM OPT', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('AUSTRIAN ACADEMY OF SCIENCES', 'AUSTRIAN ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CONSEJO SUPERIOR DE INVESTIGACIONES CIENTIFICAS (CSIC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ETH ZURICH', 'ETH')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE', 'ECOLE POLYTECH FED LAUSANNE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE PARIS SACLAY (COMUE)', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('LEIBNIZ UNIVERSITY OF HANNOVER', 'UNIVERSITY OF HANNOVER')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('COMMUNAUTE UNIVERSITY OFERSITE GRENOBLE ALPES', 'UNIVERSITY OF GRENOBLE ALPES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('KARLSRUHE INSTITUTE OF TECHNOLOGY', 'KARLSRUHE INST TECHNOL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('SCUOLA NORMALE SUPERIORE DI PISA', 'SCUOLA NORMALE SUPER PISA')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST PHYS KOMPLEXER SYST', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('RUPRECHT KARL UNIVERSITY HEIDELBERG', 'UNIVERSITY OF HEIDELBERG')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF LA SAPIENZA', 'SAPIENZA UNIVERSITY ROME')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('FORSCHUNGSZENTRUM JULICH', 'RESEARCH CENTER JULICH')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ROYAL INSTITUTE OF TECHNOLOGY', 'ROYAL INST TECHNOL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE TOULOUSE III - PAUL SABATIER', 'UNIVERSITY OFERSITE DE TOULOUSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CNRS - INSTITUTE OF CHEMISTRY (INC)', 'CNRS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('RHEIN WESTFAL TH AACHEN', 'RWTH AACHEN UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF GRENOBLE ALPES', 'UNIVERSITY OFERSITE GRENOBLE ALPES (UGA)')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('PALACKY UNIVERSITY OLOMOUC', 'PALACKY UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF PARIS SUD - PARIS XI', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE TOULOUSE', 'UNIVERSITY OF TOULOUSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('SORBONNE UNIVERSITY OFERSITE', 'SORBONNE UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('SORBONNE UNIVERSITY OF UPMC PARIS VI', 'SORBONNE UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('SORBONNE UNIVERSITY OFERSITES (COMUE)', 'SORBONNE UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UPMC SORBONNE UNIVERSITY', 'SORBONNE UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HUNGARIAN ACADEMY OF SCIENCES', 'HUNGARIAN ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HUMBOLDT UNIVERSITY OF BERLIN', 'HUMBOLDT UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE TOULOUSE III - PAUL SABATIER', 'UNIVERSITY OF TOULOUSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('BARCELONA INSTITUTE OF SCIENCE & TECHNOLOGY', 'BARCELONA INST SCI & TECHNOL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('PHYSIKALISCH-TECHNISCHE BUNDESANSTALT (PTB)', 'PHYS TECH BUNDESANSTALT')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF GRENOBLE 1', 'UNIVERSITY OF GRENOBLE ALPES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE GRENOBLE ALPES (UGA)', 'UNIVERSITY OF GRENOBLE ALPES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('TECHNISCHE UNIVERSITY OFERSITAT DRESDEN', 'DRESDEN UNIVERSITY OF TECHNOLOGY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CZECH ACADEMY OF SCIENCES', 'ACAD SCI CZECH REPUBLIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('COMMUNAUTE UNIVERSITY OFERSITE GRENOBLE ALPES', 'UNIVERSITY OF GRENOBLE ALPES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ABDUS SALAM INTERNATIONAL CENTRE FOR THEORETICAL PHYSICS (ICTP)', 'ABDUS SALAAM INT CTR THEORET PHYS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF PARIS 11', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('KATHOLIEKE UNIVERSITY OF LEUVEN', 'KU LEUVEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLYTECHNIC UNIVERSITY OF MILAN', 'POLITECN MILAN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ISTITUTO NANOSCIENZE (NANO-CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CONSIGLIO NAZIONALE DELLE RICERCHE (CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CNRS - INSTITUTE OF PHYSICS (INP)', 'CNRS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF COMPLUTENSE MADRID', 'UNIVERSITY OF COMPLUTENSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE SORBONNE PARIS CITE-USPC (COMUE)', 'SORBONNE UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST SOLID STATE RES', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('STFC RUTHERFORD APPLETON LABORATORY', 'RUTHERFORD APPLETON LAB')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF CLAUDE BERNARD - LYON 1', 'UNIVERSITY OF LYON')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF LYON 1', 'UNIVERSITY OF LYON')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CHALMERS UNIVERSITY OF TECHNOLOGY', 'CHALMERS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('FRIEDRICH SCHILLER UNIVERSITY OF JENA', 'UNIVERSITY OF JENA')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('LUDWIG MAXIMILIANS UNIVERSITY OF MUNCHEN', 'UNIVERSITY OF MUNICH')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF PARIS 11', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST FESTKORPERFORSCH', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF BORDEAUX 1', 'UNIVERSITY OF BORDEAUX')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE BORDEAUX', 'UNIVERSITY OF BORDEAUX')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE FEDERALE TOULOUSE MIDI-PYRENEES (COMUE)', 'UNIVERSITY OF TOULOUSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE TOULOUSE', 'UNIVERSITY OF TOULOUSE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE STRASBOURG', 'UNIVERSITY OF STRASBOURG')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITES DE STRASBOURG ETABLISSEMENTS ASSOCIES', 'UNIVERSITY OF STRASBOURG')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE STRASBOURG', 'UNIVERSITY OF STRASBOURG')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('BASQUE FOUNDATION FOR SCIENCE', 'BASQUE FDN SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSIDADE DE LISBOA', 'UNIVERSITY OF LISBON')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST QUANTUM OPT', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST SCI LIGHT', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('INSTITUTE OF PHYSICS - POLISH ACADEMY OF SCIENCES', 'POLISH ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLISH ACADEMY OF SCIENCES', 'POLISH ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('DORTMUND UNIVERSITY OF TECHNOLOGY', 'UNIVERSITY OF DORTMUND')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('INSTITUT DE CIENCIES FOTONIQUES (ICFO)', 'ICFO')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ICFO INST CIENCIES FOTON', 'ICFO')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('EBERHARD KARLS UNIVERSITY OF TUBINGEN', 'UNIVERSITY OF TUBINGEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLYTECHNIC UNIVERSITY OF TURIN', 'POLITECN TURIN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CEA SACLAY', 'CEA')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('SLOVAK ACADEMY OF SCIENCES', 'SLOVAK ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('KARLSRUHE INSTITUTE OF TECHNOLOGY', 'UNIVERSITY OF KARLSRUHE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('PAUL SCHERRER INSTITUTE', 'PAUL SCHERRER INST') 
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ISTITUTO NANOSCIENZE (NANO-CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF PARIS SUD - PARIS XI', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF GRENOBLE 1', 'UNIVERSITY OF GRENOBLE ALPES')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLYTECHNIC UNIVERSITY OF MILAN', 'POLITECN MILAN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF LONDON IMPERIAL COLL SCI TECHNOL & MEDICAL', 'IMPERIAL COLLEGE LONDON')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ISTITUTO NAZIONALE DI OTTICA (INO-CNR)', 'CNR')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('INSTITUTE OF PHYSICS OF THE CZECH ACADEMY OF SCIENCES', 'ACAD SCI CZECH REPUBLIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIA DE MATERIALES DE BARCELONA (ICMAB)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIA DE MATERIALES DE MADRID (ICMM)', 'CISC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO ANDALUZ DE BIOLOGIA MOLECULAR Y MEDICINA REGENERATIVA (CABIMER)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE ASTROBIOLOGIA (INTA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE BIOLOGIA MOLECULAR SEVERO OCHOA (CBM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE CIENCIAS MEDIOAMBIENTALES (CCMA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE EDAFOLOGIA Y BIOLOGIA APLICADA DEL SEGURA (CEBAS)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE FISICA MIGUEL A. CATALAN (CFMAC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE INVESTIGACION EN NANOMATERIALES Y NANOTECNOLOGIA (CINN)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE INVESTIGACION Y DESARROLLO PASCUAL VILA (CID-CSIC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE INVESTIGACIONES BIOLOGICAS (CIB)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO DE QUIMICA Y MATERIALES DE ARAGON (CEQMA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO MEDITERRANEO DE INVESTIGACIONES MARINAS Y AMBIENTALES (CMIMA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO NACIONAL DE ACELERADORES (CNA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO NACIONAL DE BIOTECNOLOGIA (CNB)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - CENTRO NACIONAL DE MICROELECTRONICA (CNM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - ESTACION EXPERIMENTAL DE AULA DEI (EEAD)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - ESTACION EXPERIMENTAL DE ZONAS ARIDAS (EEZA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - ESTACION EXPERIMENTAL DEL ZAIDIN (EEZ)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - GEOCIENCIAS BARCELONA (GEO3BCN)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO ANDALUZ DE CIENCIAS DE LA TIERRA (IACT)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE ACUSTICA (IA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE AGRICULTURA SOSTENIBLE (IAS)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE ASTROFISICA DE ANDALUCIA (IAA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE BIOMEDICINA Y BIOTECNOLOGIA DE CANTABRIA (IBBTEC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE BIOQUIMICA VEGETAL Y FOTOSINTESIS (IBVF)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CARBOQUIMICA (ICB)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CATALISIS Y PETROLEOQUIMICA (ICP)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CERAMICA Y VIDRIO (ICV)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIA & TECNOLOGIA DE POLIMEROS (ICTP)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIAS AGRARIAS (ICA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIAS DEL ESPACIO (ICE)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIAS DEL MAR (ICM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIAS MARINAS DE ANDALUCIA (ICMAN)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE CIENCIAS MATEMATICAS (ICMAT)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE ESTRUCTURA DE LA MATERIA (IEM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE FISICA APLICADA (IFA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE FISICA CORPUSCULAR (IFIC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE FISICA DE CANTABRIA (IFCA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE FISICA FUNDAMENTAL (IFF)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE INVESTIGACION EN RECURSOS CINEGETICOS (IREC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE INVESTIGACIONES BIOMEDICAS ALBERTO SOLS (IIBM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE INVESTIGACIONES MARINAS (IIM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE MATEMATICAS FISICA FUNDAMENTAL (IMAFF)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE MICROELECTRONICA DE BARCELONA (IMB-CNM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE MICROELECTRONICA DE MADRID (IMM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE MICROELECTRONICA DE SEVILLA (IMS-CNM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE OPTICA (DAZA DE VALDES)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE PRODUCTOS LACTEOS DE ASTURIAS (IPLA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE PRODUCTOS NATURALES Y AGROBIOLOGIA (IPNA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE QUIMICA AVANZADA DE CATALUNA (IQAC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE QUIMICA FISICA ROCASOLANO (IQFR)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE QUIMICA MEDICA (IQM)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE QUIMICA ORGANICA GENERAL (IQOG)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE RECURSOS NATURALES Y AGROBIOLOGIA DE SALAMANCA (IRNASA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO DE TECNOLOGIAS FISICAS Y DE LA INFORMACION (ITEFI)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - INSTITUTO MEDITERRANEO DE ESTUDIOS AVANZADOS (IMEDEA)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('INFN', 'IST NAZL FIS NUCL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('NATIONAL PHYSICAL LABORATORY - UK', 'NATL PHYS LAB')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CHALMERS UNIVERSITY OF TECHNOL', 'CHALMERS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('POLITECN TURIN', 'POLITECN TORINO')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CSIC - UAM - INSTITUT DE FISICA TEORICA (IFT)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('TECHNISCHE UNIVERSITY OFERSITAT WIEN', 'TU WIEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CENTER FOR THEORETICAL PHYSICS - POLISH ACADEMY OF SCIENCES', 'POLISH ACAD SCI')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST KERNPHYS', 'MAX PLANCK SOCIETY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITAT SIEGEN', 'UNIVERSITY OF SIEGEN')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CTR UNIVERSITY OF PARIS SUD', 'UNIVERSITY OF PARIS SACLAY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('WROCLAW UNIVERSITY OF SCIENCE & TECHNOLOGY', 'WARSAW UNIVERSITY OF TECHNOL')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('CZECH TECHNICAL UNIVERSITY PRAGUE', 'CZECH TECH UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('JOHANNES KEPLER UNIVERSITY OF LINZ', 'JOHANNES KEPLER UNIVERSITY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('PAUL DRUDE INSTITUTE FOR SOLID STATE ELECTRONICS', 'PAUL DRUDE INST FESTKORPERELEKT')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE LIBRE DE BRUXELLES', 'FREE UNIVERSITY OF BRUSSELS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE LILLE', 'UNIVERSITY OF LILLE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF LILLE 1', 'UNIVERSITY OF LILLE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('DEUTSCHES ELEKTRONEN-SYNCHROTRON (DESY)', 'DESY')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HEINRICH HEINE UNIVERSITY DUSSELDORF', 'UNIVERSITY OF DUSSELDORF')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSIDADE DE COIMBRA', 'UNIVERSITY OF COIMBRA')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ECOLE NORMALE SUPERIEURE (ENS)', 'ENS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ECOLE NORMALE SUPERIEURE DE PARIS', 'ENS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('JOZEF STEFAN INSTITUTE', 'JOZEF STEFAN INST')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('ECHNISCHE UNIVERSITY OFERSITAT CHEMNITZ', 'TECH UNIVERSITY OF CHEMNITZ')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITE DE LORRAINE', 'UNIVERSITY OF LORRAINE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('INSTITUTO DE CIENCIA DE MATERIALES DE SEVILLA (ICMS-CSIC)', 'CSIC')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('MAX PLANCK INST MATH SCI', 'MAX PLANCK SOCIETY')   
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSITA DI MODENA E REGGIO EMILIA', 'UNIVERSITY OF MODENA & REGGIO EMILIA')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OF FLORENCE', 'UNIVERSITY OF FIRENZE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('VRIJE UNIVERSITY OFERSITEIT BRUSSEL', 'FREE UNIVERSITY OF BRUSSELS')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HELMHOLTZ-ZENTRUM FUER MATERIALIEN UND ENERGIE GMBH (HZB)', 'HELMHOLTZ ZENTRUM BERLIN MAT & ENERGIE')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HEWLETT PACKARD LABS', 'HEWLETT PACKARD')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('VRIJE UNIVERSITY OFERSITEIT AMSTERDAM', 'VRIJE UNIVERSITY OF AMSTERDAM')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('UNIVERSITY OFERSIDADE DO PORTO', 'UNIVERSITY OF PORTO')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('HELMHOLTZ ZENTRUM BERLIN MAT & ENERGIE', 'HELMHOLTZ ASSOCIATION')
inst['final_standardized_organization'] = inst['final_standardized_organization'].replace('NATIONAL INSTITUTE OF STANDARDS  TECHNOLOGY NIST  USA', 'NIST')

# Check the changes
inst[['organization', 'standardized_organization','final_standardized_organization']].head()

,organization,standardized_organization,final_standardized_organization
0,UNIV PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
1,UNIV PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
2,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
3,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
4,UNIV DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM

In [9]:
inst.final_standardized_organization.value_counts()

final_standardized_organization
CNRS                            11977
UNIVERSITY OF PARIS SACLAY       5272
CNR                              4325
UNIVERSITY OF GRENOBLE ALPES     3760
MAX PLANCK SOCIETY               2740
                                ...
IKERBASQUE FDN                      1
ERWIN SCHRODINGER INST              1
MAX PLANCK INST EVOLUT BIOL         1
MINAKEM RECH                        1
DELHI TECHNOL UNIVERSITY            1
Name: count, Length: 7448, dtype: int64

In [7]:
# inst.to_csv('../05_허지수박사/quant_inst_ed_eu_fixed.csv', encoding='ISO-8859-1')
inst.to_csv('QuanTech_R/R file/quant_inst_ed_eu_fixed.csv', encoding='ISO-8859-1', index=False)

In [8]:
inst = pd.read_csv('QuanTech_R/R file/quant_inst_ed_eu_fixed.csv')
inst.final_standardized_organization.nunique()

7448

# Revised version with mapping country, city, organization name

In [14]:
import pandas as pd
from fuzzywuzzy import process
import re
from concurrent.futures import ThreadPoolExecutor
from collections import defaultdict

# 데이터 다시 불러오기
data = pd.read_csv('QuanTech_R/R file/quant_inst_ed_eu_fixed.csv')
print(data.final_standardized_organization.nunique())

# Step 1: Standardize Institution Names
def standardize_name(name):
    name = name.upper().strip()
    name = re.sub(r'\bUNIV\b', 'UNIVERSITY', name)
    name = re.sub(r'\bINST\b', 'INSTITUTE', name)
    name = re.sub(r'\bTECH\b', 'TECHNOLOGY', name)
    name = re.sub(r'\bNATL\b', 'NATIONAL', name)
    name = re.sub(r'\bCTR\b', 'CENTER', name)
    name = re.sub(r'\bSCI\b(?!ENCE)', 'SCIENCE', name)  # SCI를 SCIENCE로 통일하되 SCIENCE는 제외
    name = re.sub(r'\bSCIENTE\b', 'SCIENCE', name)  # SCIENTE를 SCIENCE로 통일
    name = re.sub(r'\bINSTITUTE SCIENCE\b', 'INSTITUTE OF SCIENCE', name)  # INSTITUTE SCIENCE를 INSTITUTE OF SCIENCE로 통일
    name = re.sub(r'\bPATRAS\b', 'PATRAS', name)  # PATRAS를 정확히 유지
#    name = re.sub(r'\bOF\b', '', name)  # "OF" 삭제
    name = re.sub(r'\b&\b', 'AND', name)  # "&"를 "AND"로 변경
    name = re.sub(r'\bUNI\b', 'UNIVERSITY', name)  # "UNI"를 "UNIVERSITY"로 변경
    name = re.sub(r'\s+', ' ', name)
    name = re.sub(r'[^\w\s]', '', name)  # 알파벳과 숫자 이외의 모든 문자를 제거
    return name

# Apply standardization
data['standardized_organization'] = data['final_standardized_organization'].astype(str).apply(standardize_name)
data['standardized_country'] = data['country'].astype(str).apply(standardize_name)
data['standardized_city'] = data['city'].astype(str).apply(standardize_name)

# Combine organization, country, and city for more accurate grouping
data['combined_info'] = data['standardized_organization'] + ", " + data['standardized_city'] + ", " + data['standardized_country']

# Step 2: Expanded Manual Mapping for Direct Grouping
manual_mapping = {
    "MIT, CAMBRIDGE, UNITED STATES": "MIT",
    "MASS INSTITUTE TECH, CAMBRIDGE, UNITED STATES": "MIT",
    "MASSACHUSETTS INST TECH, CAMBRIDGE, UNITED STATES": "MIT",
    "MASSACHUSETTS INSTITUTE OF TECHNOLOGY MIT, CAMBRIDGE, UNITED STATES": "MIT",
    "MASSACHUSETTS INSTITUTE OF TECHNOLOGY, CAMBRIDGE, UNITED STATES": "MIT",
        
    "CALTECH, PASADENA, UNITED STATES": "CALIFORNIA INSTITUTE OF TECHNOLOGY",
    "CALIFORNIA INST TECH, PASADENA, UNITED STATES": "CALIFORNIA INSTITUTE OF TECHNOLOGY",
    "STANFORD UNIVERSITY, STANFORD, UNITED STATES": "STANFORD UNIVERSITY",
    "STANFORD UNIV, STANFORD, UNITED STATES": "STANFORD UNIVERSITY",
    "STANFORD U, STANFORD, UNITED STATES": "STANFORD UNIVERSITY",
    "UC BERKELEY, BERKELEY, UNITED STATES": "UNIVERSITY OF CALIFORNIA BERKELEY",
    "UNIV CALIFORNIA BERKELEY, BERKELEY, UNITED STATES": "UNIVERSITY OF CALIFORNIA BERKELEY",
    "BERKELEY, BERKELEY, UNITED STATES": "UNIVERSITY OF CALIFORNIA BERKELEY",
    "UC SAN DIEGO, SAN DIEGO, UNITED STATES": "UNIVERSITY OF CALIFORNIA SAN DIEGO",
    "UNIV CALIFORNIA SAN DIEGO, SAN DIEGO, UNITED STATES": "UNIVERSITY OF CALIFORNIA SAN DIEGO",
    "USC, LOS ANGELES, UNITED STATES": "UNIVERSITY OF SOUTHERN CALIFORNIA",
    "UNIV SOUTHERN CALIFORNIA, LOS ANGELES, UNITED STATES": "UNIVERSITY OF SOUTHERN CALIFORNIA",
    "SOUTHERN CALIFORNIA UNIVERSITY, LOS ANGELES, UNITED STATES": "UNIVERSITY OF SOUTHERN CALIFORNIA",
    "UNIVERSITY PATRAS, PATRAS, GREECE": "UNIVERSITY OF PATRAS",
    "UNIV PATRAS, PATRAS, GREECE": "UNIVERSITY OF PATRAS",
    "UNIVERSITY PATRAS, PATRAS, GREECE": "UNIVERSITY OF PATRAS",
    "UNIV DURHAM, DURHAM, UNITED KINGDOM": "UNIVERSITY OF DURHAM",
    "OXFORD UNIVERSITY, OXFORD, UNITED KINGDOM": "UNIVERSITY OF OXFORD",
    "UNIV OXFORD, OXFORD, UNITED KINGDOM": "UNIVERSITY OF OXFORD",
    "CAMBRIDGE UNIVERSITY, CAMBRIDGE, UNITED KINGDOM": "UNIVERSITY OF CAMBRIDGE",
    "UNIV CAMBRIDGE, CAMBRIDGE, UNITED KINGDOM": "UNIVERSITY OF CAMBRIDGE",
    "HARVARD, CAMBRIDGE, UNITED STATES": "HARVARD UNIVERSITY",
    "HARVARD U, CAMBRIDGE, UNITED STATES": "HARVARD UNIVERSITY",
    "COLUMBIA UNIV, NEW YORK, UNITED STATES": "COLUMBIA UNIVERSITY",
    "COLUMBIA, NEW YORK, UNITED STATES": "COLUMBIA UNIVERSITY",
    "UNIV TOKYO, TOKYO, JAPAN": "UNIVERSITY OF TOKYO",
    "TOKYO UNIVERSITY, TOKYO, JAPAN": "UNIVERSITY OF TOKYO",
    "U TOKYO, TOKYO, JAPAN": "UNIVERSITY OF TOKYO",
    "UNIV MANCHESTER, MANCHESTER, UNITED KINGDOM": "UNIVERSITY OF MANCHESTER",
    "MANCHESTER UNIVERSITY, MANCHESTER, UNITED KINGDOM": "UNIVERSITY OF MANCHESTER",
    "UNIV EDINBURGH, EDINBURGH, UNITED KINGDOM": "UNIVERSITY OF EDINBURGH",
    "EDINBURGH UNIVERSITY, EDINBURGH, UNITED KINGDOM": "UNIVERSITY OF EDINBURGH",
    "UNIV BRISTOL, BRISTOL, UNITED KINGDOM": "UNIVERSITY OF BRISTOL",
    "BRISTOL UNIVERSITY, BRISTOL, UNITED KINGDOM": "UNIVERSITY OF BRISTOL",
    "UNIVERSITY OF PENNSYLVANIA, PHILADELPHIA, UNITED STATES": "UNIVERSITY OF PENNSYLVANIA",
    "UPENN, PHILADELPHIA, UNITED STATES": "UNIVERSITY OF PENNSYLVANIA",
    "PENN STATE, UNIVERSITY PARK, UNITED STATES": "PENNSYLVANIA STATE UNIVERSITY",
    "PENNSYLVANIA STATE UNIVERSITY, UNIVERSITY PARK, UNITED STATES": "PENNSYLVANIA STATE UNIVERSITY",
    "UCLA, LOS ANGELES, UNITED STATES": "UNIVERSITY OF CALIFORNIA LOS ANGELES",
    "UNIV CALIFORNIA LOS ANGELES, LOS ANGELES, UNITED STATES": "UNIVERSITY OF CALIFORNIA LOS ANGELES",
    "UNIVERSITY CALIFORNIA LA, LOS ANGELES, UNITED STATES": "UNIVERSITY OF CALIFORNIA LOS ANGELES",
    "UNIV TORONTO, TORONTO, CANADA": "UNIVERSITY OF TORONTO",
    "TORONTO UNIVERSITY, TORONTO, CANADA": "UNIVERSITY OF TORONTO",
    "UNIVERSITY OF MELBOURNE, MELBOURNE, AUSTRALIA": "UNIVERSITY OF MELBOURNE",
    "MELBOURNE UNIVERSITY, MELBOURNE, AUSTRALIA": "UNIVERSITY OF MELBOURNE",
    "UNIV MELBOURNE, MELBOURNE, AUSTRALIA": "UNIVERSITY OF MELBOURNE",
    "UNIVERSITY OF SYDNEY, SYDNEY, AUSTRALIA": "UNIVERSITY OF SYDNEY",
    "SYDNEY UNIVERSITY, SYDNEY, AUSTRALIA": "UNIVERSITY OF SYDNEY",
    "UNIV SYDNEY, SYDNEY, AUSTRALIA": "UNIVERSITY OF SYDNEY",
    "IMPERIAL COLLEGE LONDON, LONDON, UNITED KINGDOM": "IMPERIAL COLLEGE LONDON",
    "IMPERIAL COLLEGE, LONDON, UNITED KINGDOM": "IMPERIAL COLLEGE LONDON",
    "ICL, LONDON, UNITED KINGDOM": "IMPERIAL COLLEGE LONDON",
    "KING'S COLLEGE LONDON, LONDON, UNITED KINGDOM": "KING'S COLLEGE LONDON",
    "KCL, LONDON, UNITED KINGDOM": "KING'S COLLEGE LONDON",
    "UNIVERSITY OF WASHINGTON, SEATTLE, UNITED STATES": "UNIVERSITY OF WASHINGTON",
    "UW, SEATTLE, UNITED STATES": "UNIVERSITY OF WASHINGTON",
    "WASHINGTON UNIVERSITY, SEATTLE, UNITED STATES": "UNIVERSITY OF WASHINGTON",
    "UNIV WASHINGTON, SEATTLE, UNITED STATES": "UNIVERSITY OF WASHINGTON",
    "UNIVERSITY OF TEXAS AT AUSTIN, AUSTIN, UNITED STATES": "UNIVERSITY OF TEXAS AT AUSTIN",
    "UT AUSTIN, AUSTIN, UNITED STATES": "UNIVERSITY OF TEXAS AT AUSTIN",
    "TEXAS UNIVERSITY AUSTIN, AUSTIN, UNITED STATES": "UNIVERSITY OF TEXAS AT AUSTIN",
    "UNIV OF TEXAS AT AUSTIN, AUSTIN, UNITED STATES": "UNIVERSITY OF TEXAS AT AUSTIN",
    "UNIVERSITY OF CHICAGO, CHICAGO, UNITED STATES": "UNIVERSITY OF CHICAGO",
    "UCHICAGO, CHICAGO, UNITED STATES": "UNIVERSITY OF CHICAGO",
    "CHICAGO UNIVERSITY, CHICAGO, UNITED STATES": "UNIVERSITY OF CHICAGO",
    "UNIV OF CHICAGO, CHICAGO, UNITED STATES": "UNIVERSITY OF CHICAGO",
    
    "NATL LAB SUPERCONDUCT": "NATIONAL LABORATORY FOR SUPERCONDUCTIVITY",
    "INST PHYSICS CAS": "INSTITUTE OF PHYSICS, CAS",
    "CTR CONDENSED MATTER PHYS": "CENTER FOR CONDENSED MATTER PHYSICS",
    "TECH UNIV HAMBURG HARBURG": "TECHNICAL UNIVERSITY OF HAMBURG",
    "ECOLE NATL SUPER ELECTROCHIM ELECTROME GRENOBLE": "ECOLE NATIONALE SUPERIEURE DE L'ELECTROCHIMIE ET DE L'ELECTROMETALLURGIE DE GRENOBLE",
    "NATL TECH UNIV ATHENS": "NATIONAL TECHNICAL UNIVERSITY OF ATHENS",
    "SPACE NAVAL WARFARE SYST CTR": "SPACE AND NAVAL WARFARE SYSTEMS CENTER",
    "GEORGIA INST TECHNOL": "GEORGIA INSTITUTE OF TECHNOLOGY",
    "GEORGIA TECH RES INST": "GEORGIA TECH RESEARCH INSTITUTE",
    "INST SCIENCE MAT RAYONNEMENT": "INSTITUTE OF MATERIAL SCIENCE AND RADIATION",
    # Add more mappings as needed
}

def manual_fix(name, country):
    if 'MASSACHUSETTS INSTITUTE OF TECHNOLOGY MIT' in name:
        return 'MIT'
    if 'CNRS' in name:
        return 'CNRS'
    if 'HEIDELBERG UNIVERSITY' in name or 'UNIVERSITY OF HEIDELBERG' in name:
        return 'UNIVERSITY OF HEIDELBERG'
    if 'UNIVERSITY OF SCIENCE TECHNOL CHINA' in name or 'UNIVERSITY OF SCIENCE TECHNOLOGY OF CHINA' in name:
        return 'UNIVERSITY OF SCIENCE AND TECHNOLOGY OF CHINA'
    if 'SECONDA UNIVERSITY OF NAPOLI' in name or 'SECONDA UNIVERSITY OFFERSITA DEGLI STUDI DI NAPOLI' in name:
        return 'SECONDA UNIVERSITY OF NAPOLI'
    if 'UNIVERSITY OF LONDON QUEEN MARY WESTFIELD COLL' in name or 'QUEEN MARY UNIVERSITY LONDON' in name or 'UNIVERSITY OF LONDON' in name:
        return 'QUEEN MARY UNIVERSITY OF LONDON'
    if 'NATIONAL ACADEMY OF SCIENCES UKRAINE' in name or 'NATIONAL ACAD SCIENCE UKRAINE' in name:
        return 'NATIONAL ACADEMY OF SCIENCES UKRAINE'
    return name

data['fixed_organization'] = data.apply(lambda row: manual_fix(row['standardized_organization'], row['standardized_country']), axis=1)

def map_manual(row):
    name = row['combined_info']
    return manual_mapping.get(name, row['standardized_organization'])

# Use ThreadPoolExecutor for faster manual mapping
with ThreadPoolExecutor(max_workers=8) as executor:
    data['grouped_organization'] = list(executor.map(map_manual, data.to_dict('records')))

data.loc[data['fixed_organization'] == 'CNRS', 'standardized_country'] = 'FRANCE'

# Step 3: Improved Fuzzy Matching to further reduce duplicates using combined info
def fuzzy_merge(df, key, threshold=90, limit=2):
    unique_names = df[key].unique()
    mappings = {}
    for name in unique_names:
        # Filter: compare strings with similar lengths
        filtered_names = [x for x in unique_names if abs(len(x) - len(name)) < 5]
        matches = process.extract(name, filtered_names, limit=limit, scorer=fuzz.token_sort_ratio)
        for match in matches:
            if match[1] >= threshold and name != match[0]:  # Ensure names are not identical
                # Check if one name contains "2ND" and the other doesn't
                if ("2ND" in name and "2ND" not in match[0]) or ("2ND" not in name and "2ND" in match[0]):
                    continue  # Skip this match to avoid incorrect merging
                # Check if one name contains "MIT" and the other contains "MASSACHUSETTS INSTITUTE OF TECHNOLOGY"
                if ("MIT" in name or "MASSACHUSETTS INSTITUTE OF TECHNOLOGY" in name):
                    mappings[name] = "MIT"
                    mappings[match[0]] = "MIT"
                    continue
                mappings[match[0]] = name
    return mappings

# Apply fuzzy matching in parallel
fuzzy_mapping = fuzzy_merge(data, 'fixed_organization')

# Apply the fuzzy mapping to the dataframe
data['final_grouped_organization'] = data['fixed_organization'].map(fuzzy_mapping).fillna(data['fixed_organization'])

data['final_grouped_organization'] = data['final_grouped_organization'].replace('CALIFORNIA INSTITUTE OF TECHNOLOGY', 'CALTECH')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('UNIVERSITY OF SCIENCE  TECHNOLOGY OF CHINA', 'UNIVERSITY OF SCIENCE  TECHNOL CHINA')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('NANYANG TECHNOLOGICAL UNIVERSITY  NATIONAL INSTITUTE OF EDUCATION NIE SINGAPORE', 'NANYANG TECHNOL UNIVERSITY')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('UNIVERSITY OF MICHIGAN SYSTEM', 'UNIVERSITY OF MICHIGAN')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('UNIVERSITY OF CALIFORNIA SYSTEM', 'UNIVERSITY OF CALIFORNIA')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('NATIONAL INSTITUTE OF STANDARDS  TECHNOLOGY NIST  USA', 'NIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('NATIONAL INSTITUTE OF STANDARDS TECHNOLOGY NIST USA', 'NIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('NATIONAL INSTITUTE INFORMAT', 'NATIONAL INSTITUTE OF INFORMATICS NII')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('UNIVERSITY OF ROME LA SAPIENZA', 'SAPIENZA UNIVERSITY ROME')

data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA INSTITUTE FOR ADVANCED STUDY KIAS', 'KIAS')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA INSTITUTE ADV STUDY', 'KIAS')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA ADV INSTITUTE OF SCIENCE  TECHNOL KAIST', 'KAIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA ADVANCED INSTITUTE OF SCIENCE  TECHNOLOGY KAIST', 'KAIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA INSTITUTE OF SCIENCE  TECHNOL', 'KIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('POHANG UNIVERSITY OF SCIENCE  TECHNOLOGY POSTECH', 'POSTECH')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA RESEARCH INSTITUTE OF STANDARDS  SCIENCE KRISS', 'KRISS')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('GWANGJU INSTITUTE OF SCIENCE  TECHNOL', 'GIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('GWANGJU INSTITUTE OF SCIENCE  TECHNOLOGY GIST', 'GIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA RES INSTITUTE STAND  SCIENCE', 'KRISS')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('POHANG UNIVERSITY OF SCIENCE  TECHNOL', 'POSTECH')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('ULSAN NATIONAL INSTITUTE OF SCIENCE  TECHNOL UNIST', 'UNIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('ULSAN NATIONAL INSTITUTE OF SCIENCE  TECHNOLOGY UNIST', 'UNIST')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('ASIA PACIFIC CENTER FOR THEORETICAL PHYSICS', 'APCTP')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('ASIA PACIFIC CENTER THEORET PHYS', 'APCTP')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA INSTITUTE OF SCIENCE  TECHNOL INFORMAT', 'KISTI')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('KOREA INSTITUTE OF SCIENCE  TECHNOLOGY INFORMATION KISTI', 'KISTI')
data['final_grouped_organization'] = data['final_grouped_organization'].replace('SAMSUNG ADV INSTITUTE TECHNOL', 'SAMSUNG')

data.loc[data['organization'] == 'UNIV TORONTO', 'final_grouped_organization'] = 'UNIVERSITY OF TORONTO'
data.loc[data['organization'] == 'UNIVERSITY OF TORONTO', 'final_grouped_organization'] = 'UNIVERSITY OF TORONTO'
data.loc[data['organization'] == 'UNIV PORTO', 'final_grouped_organization'] = 'UNIVERSITY OF PORTO'
data.loc[data['organization'] == 'UNIVERSIDADE DO PORTO', 'final_grouped_organization'] = 'UNIVERSITY OF PORTO'
data.loc[data['organization'] == 'KOREA UNIV', 'final_grouped_organization'] = 'KOREA UNIVERSITY'
data.loc[data['organization'] == 'KOREA UNIVERSITY', 'final_grouped_organization'] = 'KOREA UNIVERSITY'
data.loc[data['organization'] == 'INST FOR BASIC SCI KOREA', 'final_grouped_organization'] = 'KBSI'
data.loc[data['organization'] == 'INSTITUTE FOR BASIC SCIENCE - KOREA (IBS)', 'final_grouped_organization'] = 'KBSI'
data.loc[data['organization'] == 'KOREA BASIC SCIENCE INSTITUTE (KBSI)', 'final_grouped_organization'] = 'KBSI'

data.loc[data['organization'] == 'GHENT UNIV GLOBAL CAMPUS', 'final_grouped_organization'] = 'GHENT UNIVERSITY'
data.loc[data['organization'] == 'GHENT UNIVERSITY', 'final_grouped_organization'] = 'GHENT UNIVERSITY'
data.loc[data['organization'] == 'INST BASIC SCI', 'final_grouped_organization'] = 'INSTITUTE BASIC SCIENCE'
data.loc[data['organization'] == 'INST BASIC SCI IBS', 'final_grouped_organization'] = 'INSTITUTE BASIC SCIENCE'
data.loc[data['organization'] == 'KOREA ADV INST SCI & TECHNOL KAIST', 'final_grouped_organization'] = 'KAIST'

data.loc[data['organization'] == 'KOREA ELECTROTECHNOLOGY RESEARCH INSTITUTE (KERI)', 'final_grouped_organization'] = 'KERI'
data.loc[data['organization'] == 'KOREA ELECTROTECHNOL RES INST', 'final_grouped_organization'] = 'KERI'

data.loc[data['organization'] == 'ELECT & TELECOMMUN RES INST', 'final_grouped_organization'] = 'ETRI'
data.loc[data['organization'] == 'ELECTRONICS & TELECOMMUNICATIONS RESEARCH INSTITUTE', 'final_grouped_organization'] = 'ETRI'
 
data.loc[data['standardized_organization'] == 'NATIONAL INSTITUTE FOR MATHEMATICAL SCIENCES NIMS', 'final_grouped_organization'] = 'NIMS'
data.loc[data['organization'] == 'NATL INST MAT SCI', 'final_grouped_organization'] = 'NIMS'

data.loc[data['organization'] == 'KOREA INST MACHINERY & MAT', 'final_grouped_organization'] = 'KIMM'
data.loc[data['organization'] == 'KOREA INSTITUTE OF MACHINERY & MATERIALS', 'final_grouped_organization'] = 'KIMM'

data.loc[data['organization'] == 'KOREA INSTITUTE OF SCIENCE & TECHNOLOGY (KIST)', 'final_grouped_organization'] = 'KIST'

data.loc[data['organization_clean'] == 'ELECTRONICS  TELECOMMUNICATIONS RESEARCH INSTITUTE  KOREA ETRI', 'final_grouped_organization'] = 'ETRI'

data.loc[data['organization'] == 'OBSERV PARIS', 'final_grouped_organization'] = 'OBSERVATOIRE DE PARIS'

data.loc[data['grouped_organization'] == 'TU WIEN', 'final_grouped_organization'] = 'TECHNOLOGY UNIVERSITY OF WIEN'

data.loc[data['organization'] == 'INST ELECTR MAT TECHNOL', 'final_grouped_organization'] = 'INSTITUTE OF ELECTRONIC MATERIALS TECHNOLOGY'

data.loc[data['organization'] == 'HEWLETT-PACKARD', 'final_grouped_organization'] = 'HP'
data.loc[data['organization'] == 'HEWLETT PACKARD', 'final_grouped_organization'] = 'HP'

data.loc[data['organization'] == 'RES ORG INFORMAT & SYST', 'final_grouped_organization'] = 'ROIS'
data.loc[data['organization'] == 'RESEARCH ORGANIZATION OF INFORMATION & SYSTEMS (ROIS)', 'final_grouped_organization'] = 'ROIS'

# Save the refined data to a CSV file
data[['qc_category','pubid','pubyear','institution_id_te','organization', 'country', 'city', 'final_standardized_organization','standardized_organization', 'standardized_country', 'standardized_city', 'grouped_organization', 'final_grouped_organization']].to_csv('QuanTech_R/R file/quant_inst_ed_eu_fixed_standardized.csv', index=False)

# Display the first few rows of the dataframe and the path
print(data.final_grouped_organization.nunique())
data[['organization', 'country', 'city', 'final_standardized_organization','standardized_organization', 'standardized_country', 'standardized_city', 'grouped_organization', 'final_grouped_organization']].head()

7448
7297

,organization,country,city,final_standardized_organization,standardized_organization,standardized_country,standardized_city,grouped_organization,final_grouped_organization
0,UNIV PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
1,UNIV PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
2,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
3,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
4,UNIV DURHAM,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM

In [46]:
data.loc[data.country=="SOUTH KOREA"].final_grouped_organization.unique()

array(['SEOUL NATIONAL UNIVERSITY', 'LG ELECT INSTITUTE TECHNOL',
       'HANYANG UNIVERSITY', 'KYUNG HEE UNIVERSITY', 'POSTECH',
       'YONSEI UNIVERSITY', 'KIST', 'KRISS', 'CHUNG ANG UNIVERSITY',
       'AJOU UNIVERSITY', 'PUSAN NATIONAL UNIVERSITY', 'UNIST', 'GIST',
       'KIAS', 'KAIST', 'MOKPO NATIONAL UNIVERSITY',
       'HANYANG UNIVERSITY OF ERICA', 'KONGJU NATIONAL UNIVERSITY',
       'JEONBUK NATIONAL UNIVERSITY', 'CHUNGBUK NATIONAL UNIVERSITY',
       'APCTP', 'KBSI', 'KOREA UNIVERSITY', 'EWHA WOMANS UNIVERSITY',
       'KERI', 'UTP UNIVERSITY OF SCIENCE  TECHNOL', 'SOHAG UNIVERSITY',
       'SUNGKYUNKWAN UNIVERSITY', 'ETRI',
       'ELECTRONICS  TELECOMMUNICATIONS RESEARCH INSTITUTE  KOREA ETRI',
       'YEUNGNAM UNIVERSITY', 'KONKUK UNIVERSITY', 'KISTI', 'NIMS',
       'NATIONAL INSTITUTE MAT SCIENCE',
       'INSTITUTE FOR BASIC SCIENCE KOREA', 'ASML KOREA', 'SAMSUNG',
       'SAMSUNG ELECT', 'DONGGUK UNIVERSITY', 'INHA UNIVERSITY',
       'SEJONG UNIVERSITY', 'KOREA ELECT TECHNOL INSTITUTE',
       'PUKYONG NATIONAL UNIVERSITY',
       'GUMI ELECTRON  INFORMAT TECHNOL RES INSTITUTE',
       'HONGIK UNIVERSITY', 'KYUNGPOOK NATIONAL UNIVERSITY',
       'DIV ADV MAT SCIENCE POSTECH',
       'KOREA NATIONAL UNIVERSITY OF TRANSPORTAT',
       'PUSAN NATIONAL UNIVERSITY HOSPITAL',
       'CHUNGNAM NATIONAL UNIVERSITY', 'KIMM',
       'CHONBUK NATIONAL UNIVERSITY',
       'DAEGU GYEONGBUK INSTITUTE OF SCIENCE  TECHNOLOGY DGIST', 'DGIST',
       'KOREA INSTITUTE OF MACHINERY  MATERIALS', 'UNIVERSITY OF ULSAN',
       'IND TECHNOL RES INSTITUTE',
       'KOREA INSTITUTE OF INDUSTRIAL TECHNOLOGY KITECH',
       'SOOKMYUNG WOMENS UNIVERSITY',
       'DAEGU GYEONGBUK INSTITUTE OF SCIENCE  TECHNOL',
       'CENTER QUANTUM NANOSCI', 'CNRS', 'POSCO',
       'KOREA ADV NANOFABRICAT CENTER',
       'KOREA ELECTRONICS TECHNOLOGY INSTITUTE KETI',
       'CHONNAM NATIONAL UNIVERSITY', 'MAX PLANCK POSTECH',
       'UNIVERSITY OF SEOUL', 'GHENT UNIVERSITY',
       'INCHEON NATIONAL UNIVERSITY', 'INSTITUTE BASIC SCIENCE'],
      dtype=object)

In [47]:
data.loc[data.final_grouped_organization=='ELECTRONICS  TELECOMMUNICATIONS RESEARCH INSTITUTE  KOREA ETRI']

,Unnamed: 0,pubid,qc_category,institution_id_te,organization,suborganization,full_address,city,state,country,...,pubyear,organization_clean,standardized_organization,final_standardized_organization,standardized_country,standardized_city,combined_info,fixed_organization,grouped_organization,final_grouped_organization
107087,107088,22996605,qc421,19529755,ELECTRONICS & TELECOMMUNICATIONS RESEARCH INST...,NaN,"ELECT & TELECOMMUN RES INST, TAEJON 305700, SO...",TAEJON,NaN,SOUTH KOREA,...,2013,ETRI,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS & TELECOMMUNICATIONS RESEARCH INST...,SOUTH KOREA,TAEJON,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...
191025,191026,1464560,qc423,19524603,ELECTRONICS & TELECOMMUNICATIONS RESEARCH INST...,NaN,"ELECT & TELECOMMUN RES INST, TAEJON 305600, SO...",TAEJON,NaN,SOUTH KOREA,...,1999,ELECTRONICS & TELECOMMUNICATIONS RESEARCH INST...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS & TELECOMMUNICATIONS RESEARCH INST...,SOUTH KOREA,TAEJON,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...,ELECTRONICS TELECOMMUNICATIONS RESEARCH INSTI...

In [78]:
print(data.organization.nunique())
print(data.final_standardized_organization.nunique())
print(data.final_grouped_organization.nunique())
data[['organization', 'country', 'city', 'final_standardized_organization','standardized_organization', 'standardized_country', 'standardized_city', 'grouped_organization', 'final_grouped_organization']].drop_duplicates()

9985
7449
7306

,organization,country,city,final_standardized_organization,standardized_organization,standardized_country,standardized_city,grouped_organization,final_grouped_organization
0,UNIV PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
2,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS,GREECE,PATRAS,UNIVERSITY OF PATRAS,UNIVERSITY OF PATRAS
4,UNIV DURHAM,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM
5,DURHAM UNIVERSITY,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM,ENGLAND,DURHAM,UNIVERSITY OF DURHAM,UNIVERSITY OF DURHAM
6,UNIVERSITE LIBRE DE BRUXELLES,BELGIUM,BRUSSELS,FREE UNIVERSITY OF BRUSSELS,FREE UNIVERSITY OF BRUSSELS,BELGIUM,BRUSSELS,FREE UNIVERSITY OF BRUSSELS,FREE UNIVERSITY OF BRUSSELS
...,...,...,...,...,...,...,...,...,...
244909,CHINESE ACADEMY OF AGRICULTURAL SCIENCES,PEOPLES R CHINA,CHENGDU,CHINESE ACADEMY OF AGRICULTURAL SCIENCES,CHINESE ACADEMY OF AGRICULTURAL SCIENCES,PEOPLES R CHINA,CHENGDU,CHINESE ACADEMY OF AGRICULTURAL SCIENCES,CHINESE ACADEMY OF AGRICULTURAL SCIENCES
244910,"INSTITUTE OF URBAN AGRICULTURE, CAAS",PEOPLES R CHINA,CHENGDU,"INSTITUTE OF URBAN AGRICULTURE, CAAS",INSTITUTE OF URBAN AGRICULTURE CAAS,PEOPLES R CHINA,CHENGDU,INSTITUTE OF URBAN AGRICULTURE CAAS,INSTITUTE OF URBAN AGRICULTURE CAAS
244925,SHENZHEN JL COMPUTAT SCI & APPL RES INST,PEOPLES R CHINA,SHENZHEN,SHENZHEN JL COMPUTAT SCI & APPL RES INST,SHENZHEN JL COMPUTAT SCIENCE APPL RES INSTITUTE,PEOPLES R CHINA,SHENZHEN,SHENZHEN JL COMPUTAT SCIENCE APPL RES INSTITUTE,SHENZHEN JL COMPUTAT SCIENCE APPL RES INSTITUTE
244931,DELHI TECHNOL UNIV,INDIA,NEW DELHI,DELHI TECHNOL UNIVERSITY,DELHI TECHNOL UNIVERSITY,INDIA,NEW DELHI,DELHI TECHNOL UNIVERSITY,DELHI TECHNOL UNIVERSITY
244932,DELHI TECHNOLOGICAL UNIVERSITY,INDIA,NEW DELHI,TECHNOLOGICAL UNIVERSITY DUBLIN,TECHNOLOGICAL UNIVERSITY DUBLIN,INDIA,NEW DELHI,TECHNOLOGICAL UNIVERSITY DUBLIN,TECHNOLOGICAL UNIVERSITY DUBLIN

In [93]:
data[data.final_grouped_organization=='UNIVERSITY CAMBRIDGE TRINITY COLL']

Empty DataFrame
Columns: [Unnamed: 0, pubid, qc_category, institution_id_te, organization, suborganization, full_address, city, state, country, zip, pubyear, organization_clean, standardized_organization, final_standardized_organization, standardized_country, standardized_city, combined_info, grouped_organization, final_grouped_organization]
Index: []

In [ ]:
manual_mapping = {
    "MIT": "MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
    "MASS INSTITUTE OF TECH": "MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
    "CALTECH": "CALIFORNIA INSTITUTE OF TECHNOLOGY",
    "CALIFORNIA INST OF TECH": "CALIFORNIA INSTITUTE OF TECHNOLOGY",
    "STANFORD UNIVERSITY": "STANFORD",
    "STANFORD UNIV": "STANFORD",
    "UC BERKELEY": "UNIVERSITY OF CALIFORNIA BERKELEY",
    "UNIV OF CALIFORNIA BERKELEY": "UNIVERSITY OF CALIFORNIA BERKELEY",
    "UC SAN DIEGO": "UNIVERSITY OF CALIFORNIA SAN DIEGO",
    "UNIV OF CALIFORNIA SAN DIEGO": "UNIVERSITY OF CALIFORNIA SAN DIEGO",
    "USC": "UNIVERSITY OF SOUTHERN CALIFORNIA",
    "UNIV OF SOUTHERN CALIFORNIA": "UNIVERSITY OF SOUTHERN CALIFORNIA",
    "UNIV PATRAS": "UNIVERSITY OF PATRAS",
    "UNIV DURHAM": "UNIVERSITY OF DURHAM",
    # Add more mappings as needed
}

In [89]:
def remove_duplicates(standardization_dict):
    seen_values = set()
    unique_standardization = {}
    
    for key, value in standardization_dict.items():
        if value not in seen_values:
            unique_standardization[key] = value
            seen_values.add(value)
    
    return unique_standardization

manual_standardization = remove_duplicates(manual_standardization)

len(manual_standardization)

206

In [71]:
def remove_duplicates(standardization_dict):
    seen_values = set()
    unique_standardization = {}
    
    for key, value in standardization_dict.items():
        if value not in seen_values:
            unique_standardization[key] = value
            seen_values.add(value)
    
    return unique_standardization

manual_standardization = remove_duplicates(manual_standardization)

len(manual_standardization)

279